[package]
name = "radium"
version = "1.0.0"
authors = ["Zacchary Dempsey-Plante <zacc@ztdp.ca>"]
edition = "2021"
license = "GPL-3.0-or-later"
description = "A simple music & dice bot made for personal use."

[dependencies]
anyhow = "1.0"
dotenv = "0.15"
lavalink-rs = { git = "https://gitlab.com/vicky5124/lavalink-rs", features = ["rustls"] }
lazy_static = "1.4"
parse_duration = "2.1"
poise = { git = "https://github.com/kangalioo/poise" }
rand = "0.8"
regex = "1.5"
songbird = { version = "0.2", default-features = false, features = ["serenity-rustls", "gateway"] }
tokio = { version = "1.10", features = ["macros", "rt-multi-thread"] }
url = "2.2"

[patch.crates-io]
# Potentially have to run `cargo update -p serenity:<version> --precise <whatever version is in the git repo>`
serenity = { git = "https://github.com/serenity-rs/serenity", branch = "next" }
