[package]
name = "radium"
version = "0.1.0"
edition = "2018"

[dependencies]
poise = { git = "https://github.com/kangalioo/poise" }
tokio = { version = "1.10", features = ["macros", "rt-multi-thread"] }
